name: Docker CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build v9
      run: docker build --tag bshp/firefly:latest . --build-arg TOMCAT_VERSION=9 --progress=plain
    - name: Push v9
      run: |
        docker tag bshp/firefly:latest bshp/firefly:v9.11
        docker push bshp/firefly:latest
        docker push bshp/firefly:v9.11
    - name: Build v10
      run: docker build --tag bshp/firefly:v10.17 . --build-arg TOMCAT_VERSION=10 --progress=plain
    - name: Push v10
      run: |
        docker push bshp/firefly:v10.17
