name: Docker CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  schedule:
    - cron:  '15 1 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build v9.8
      run: docker build . --pull --tag bshp/firefly:v9.8 --build-arg TOMCAT_VERSION=9 --build-arg JAVA_VERSION=8 --progress=plain --no-cache
    - name: Push v9.8
      run: |
        docker push bshp/firefly:v9.8
    - name: Build v9.11
      run: docker build . --pull --tag bshp/firefly:latest --build-arg TOMCAT_VERSION=9 --progress=plain --no-cache
    - name: Push v9.11
      run: |
        docker tag bshp/firefly:latest bshp/firefly:v9.11
        docker push bshp/firefly:latest
        docker push bshp/firefly:v9.11
    - name: Build v10.17
      run: docker build . --pull --tag bshp/firefly:v10.17 --build-arg TOMCAT_VERSION=10 --progress=plain --no-cache
    - name: Push v10.17
      run: |
        docker push bshp/firefly:v10.17
    - name: Build v10.21
      run: docker build . --pull --tag bshp/firefly:v10.21 --build-arg JAVA_VERSION=21 --build-arg TOMCAT_VERSION=10 --progress=plain --no-cache
    - name: Push v10.21
      run: |
        docker push bshp/firefly:v10.21
